# Generated by Django 2.0.7 on 2019-08-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
